import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import Project from '../components/Project.jsx';
const inter = Inter({ subsets: ['latin'] })

export default function Home({data1,data2}) {
  console.log(data2);
  return (
    <div style={{display:'flex'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}>
        
      </main> */}
      <div>
      <div>
        <Image
        src={data1.avatar_url}
        height={100}
        width={100}
        alt="avatar"
        />
<p>{data1.name}</p>
<p>{data1.login}</p>
      </div>
      <div>
        <p>
        Full-stack Developer | FOSS | JavaScript<br/> | Typescript | NodeJS | Deno | <br/>ReactJS | HTML | CSS | Chakra-UI | MUI
        </p>
        <div>
        <Link href="https://drive.google.com/file/d/1v1vYxYlg6Lntui-0pEKQ_slwJPizi9DO/view?usp=share_link" target="_blank" >
        <button>
          Resume
        </button>
        </Link>
        <Link href="https://github.com/aaka8566" target="_blank" >
        <button>
          Follow
        </button>
        </Link>
      </div>
      </div>
      <div>
        <p>
          <span>Full Time Web Developer (Full Time)</span>
          <span>Masai School</span>
          <span>Bengaluru,India</span>
        </p>
      </div>
      </div>
      <div>
<h1>Projects</h1>
{data2.items.map((el)=>(
  <Project
  key={el.id}
        name={el.name}
        forks={el.forks_count}
       star={el.stargazers_count}
        lang={el.language}
        url={el.svn_url}
        />
))}


        
      </div>
    </div>
  )
}
export async function getStaticProps(){
  const re=await fetch(`https://api.github.com/users/aaka8566`);
  const re1=await re.json();
  let r=await fetch(`https://api.github.com/search/repositories?q=user:aaka8566+fork:true&sort=updated&per_page=10&type=Repositories`);
let r1=await r.json();
  return{
    props:{
      data1:re1,
      data2:r1
    }
  }
} 







// avatar_url
// : 
// "https://avatars.githubusercontent.com/u/112715657?v=4"
// bio
// : 
// null
// blog
// : 
// ""
// company
// : 
// null
// created_at
// : 
// "2022-09-02T15:34:47Z"
// email
// : 
// null
// events_url
// : 
// "https://api.github.com/users/aaka8566/events{/privacy}"
// followers
// : 
// 40
// followers_url
// : 
// "https://api.github.com/users/aaka8566/followers"
// following
// : 
// 44
// following_url
// : 
// "https://api.github.com/users/aaka8566/following{/other_user}"
// gists_url
// : 
// "https://api.github.com/users/aaka8566/gists{/gist_id}"
// gravatar_id
// : 
// ""
// hireable
// : 
// null
// html_url
// : 
// "https://github.com/aaka8566"
// id
// : 
// 112715657
// location
// : 
// "Patna,Bihar"
// login
// : 
// "aaka8566"
// name
// : 
// "Aakash Chakravarty"
// node_id
// : 
// "U_kgDOBrfniQ"
// organizations_url
// : 
// "https://api.github.com/users/aaka8566/orgs"
// public_gists
// : 
// 0
// public_repos
// : 
// 7
// received_events_url
// : 
// "https://api.github.com/users/aaka8566/received_events"
// repos_url
// : 
// "https://api.github.com/users/aaka8566/repos"
// site_admin
// : 
// false
// starred_url
// : 
// "https://api.github.com/users/aaka8566/starred{/owner}{/repo}"
// subscriptions_url
// : 
// "https://api.github.com/users/aaka8566/subscriptions"
// twitter_username
// : 
// null
// type
// : 
// "User"
// updated_at
// : 
// "2023-01-05T19:48:42Z"
// url
// : 
// "https://api.github.com/users/aaka8566"